export const accentColor = "#B0DB60";

export const idToEmotions = {
    0: "Admiration",
    1: "Adoration",
    2: "AestheticAppreciation",
    3: "Amusement",
    4: "Anger",
    5: "Anxiety",
    6: "Awe",
    7: "Awkwardness",
    8: "Boredom",
    9: "Calmness",
    10: "Concentration",
    11: "Confusion",
    12: "Contemplation",
    13: "Contentment",
    14: "Craving",
    15: "Desire",
    16: "Determination",
    17: "Disappointment",
    18: "Disgust",
    19: "Distress",
    20: "Doubt",
    21: "Embarrassment",
    22: "EmpathicPain",
    23: "Entrancement",
    24: "Envy",
    25: "Excitement",
    26: "Fear",
    27: "Guilt",
    28: "Horror",
    29: "Interest",
    30: "Joy",
    31: "Love",
    32: "Nostalgia",
    33: "Pain",
    34: "Pride",
    35: "Realization",
    36: "Relief",
    37: "Romance",
    38: "Sadness",
    39: "Satisfaction",
    40: "Shame",
    41: "Surprise (negative)",
    42: "Surprise (positive)",
    43: "Sympathy",
    44: "Tiredness",
    45: "Triumph"
}

export const emotionsToId = {
    "Admiration": 0,
    "Adoration": 1,
    "AestheticAppreciation": 2,
    "Amusement": 3,
    "Anger": 4,
    "Anxiety": 5,
    "Awe": 6,
    "Awkwardness": 7,
    "Boredom": 8,
    "Calmness": 9,
    "Concentration": 10,
    "Confusion": 11,
    "Contemplation": 12,
    "Contentment": 13,
    "Craving": 14,
    "Desire": 15,
    "Determination": 16,
    "Disappointment": 17,
    "Disgust": 18,
    "Distress": 19,
    "Doubt": 20,
    "Embarrassment": 21,
    "EmpathicPain": 22,
    "Entrancement": 23,
    "Envy": 24,
    "Excitement": 25,
    "Fear": 26,
    "Guilt": 27,
    "Horror": 28,
    "Interest": 29,
    "Joy": 30,
    "Love": 31,
    "Nostalgia": 32,
    "Pain": 33,
    "Pride": 34,
    "Realization": 35,
    "Relief": 36,
    "Romance": 37,
    "Sadness": 38,
    "Satisfaction": 39,
    "Shame": 40,
    "Surprise (negative)": 41,
    "Surprise (positive)": 42,
    "Sympathy": 43,
    "Tiredness": 44,
    "Triumph": 45
}